// <auto-generated />
namespace Hospital_management_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addtheroletotheemployeeandremoveitformdocatorandemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtheroletotheemployeeandremoveitformdocatorandemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202511292229318_add the role to the employee and remove it form docator and employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
