// <auto-generated />
namespace Hospital_management_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initialmegeration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmegeration));
        
        string IMigrationMetadata.Id
        {
            get { return "202512021430341_initial megeration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
