// <auto-generated />
namespace Hospital_management_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addtherolecolumntothedoctorandreseptionestclasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtherolecolumntothedoctorandreseptionestclasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202511292200041_add the role column to the doctor and reseptionest classes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
